# Generated by Django 2.0.13 on 2019-07-16 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_place', models.CharField(max_length=100)),
                ('arrival_place', models.CharField(max_length=100)),
                ('min_day', models.IntegerField()),
                ('max_day', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('vacation_start', models.DateField()),
                ('vacation_end', models.DateField()),
                ('notification_frequency', models.CharField(max_length=100)),
                ('go_speed', models.IntegerField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
